---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /usr/sbin/init

provisioner:
  name: ansible_playbook
  hosts: all
  playbook: site.yml
  roles_path: roles
  ansible_host_key_checking: false
  ansible_verbose: true
  ansible_verbosity: 1
  require_chef_omnibus: false

verifier:
  name: shell
  command: py.test -c pytest.ini -v --host="paramiko://${KITCHEN_USERNAME}@${KITCHEN_HOSTNAME}:${KITCHEN_PORT}?ssh_identity_file=${KITCHEN_SSH_KEY}" --junit-xml "junit-${KITCHEN_INSTANCE}.xml" "test/integration/${KITCHEN_SUITE}"
  
platforms:
  - name: centos-7
    driver_config:
      image: centos:7
      forward:
        - 8080:80
    lifecycle:
      pre_verify:
        - local: pip3 install -r requirements.txt
        - remote: sudo yum -y install python36-pip net-tools
        - remote: sudo pip3 install testinfra six

suites:
  - name: default
