---

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mlocate
    - nano
    - httpd

- name: enable and start apache
  service:
    name: httpd
    enabled: yes
    state: started

#- name: Wait for port 80 to become open on the host
#  ignore_errors: true
#  wait_for:
#    host: localhost
#    port: 80
#    timeout: 5
#    delay: 5