---

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mlocate
    - nano
    - httpd

- name: enable and start apache
  service:
    name: httpd
    enabled: yes
    state: started
    
